export const FETCH_STOCK_DATA = "FETCH_STOCK_DATA";
export const SET_GRPAH_MODE = "CHANGE_GRPAH_MODE";
export const SET_STOCK = "SET_STOCK";
export const FETCH_STOCK_INFO = "FETCH_STOCK_INFO";
export const FETCH_STOCK_PARMS = "FETCH_STOCK_PARMS";
export const FETCH_GRPAH_DATA = "FETCH_GRPAH_DATA";
